This notebook creates the TrafficPerAirport table the first time. Once created and loaded in the data warehouse it will be updated by another
notebook or script that will only retrieve new data from the API

In [1]:
import pandas as pd
import utils as u

# API Experiment

Since the dataset is so big, the ISTAC doesnt give you the option of downloading just one with all the aircraft movements (arrival, departure, all) and all the types of observed values (passenger, mail & goods, operations). For each type of aircraft movement and for each type of obs_val you have to make an API call, so if you wanted to get all the data you would need 3x3 = 9 API calls, each one retrieving essentially the same data except for the obs_value column. And the call is not fast either, trying it in the `data_exploration` notebook it lasted one minute and twenty seconds for one call

Since this code is to create the table for the first time I dont mind doing the 9 API calls, however in the pipeline...

Wait a minute, in the pipeline I will only be retreiving the last month so it should be no problem. Try the API call bringing only the last month to see how long it last, if its fast then I dont mind retreiving the three `Total` tables (where aircraft movement is total). But if it is slow then only retrieve `Arrival` and `Departure`

In [64]:
# url only last month for experiment
url_lm = "https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00017A_000001/~latest.csv?representation=TIME_PERIOD[~last=1]&granularity=TIME_PERIOD[M]"

In [65]:
d = pd.read_csv(u.get_data_from_API_call(url_lm))

In [66]:
d['TIME_PERIOD#es']

0        07/2025
1        07/2025
2        07/2025
3        07/2025
4        07/2025
          ...
10579    07/2025
10580    07/2025
10581    07/2025
10582    07/2025
10583    07/2025
Name: TIME_PERIOD#es, Length: 10584, dtype: object

Okay, confirmed it is fast, so we can make the nine calls withouth worries

# Creating table TrafficPerAirport

In [2]:
pass_t = "https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00017A_000001/~latest.csv?granularity=TIME_PERIOD[M]&lang=en"
gm_t = "https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00017A_000002/~latest.csv?granularity=TIME_PERIOD[M]&lang=en"
op_t = "https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00017A_000003/~latest.csv?granularity=TIME_PERIOD[M]&lang=en"

pass_arr = "https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00017A_000004/~latest.csv?granularity=TIME_PERIOD[M]&lang=en"
gm_arr = "https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00017A_000005/~latest.csv?granularity=TIME_PERIOD[M]&lang=en"
op_arr = "https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00017A_000006/~latest.csv?granularity=TIME_PERIOD[M]&lang=en"

pass_depar = "https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00017A_000007/~latest.csv?granularity=TIME_PERIOD[M]&lang=en"
gm_depar = "https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00017A_000008/~latest.csv?granularity=TIME_PERIOD[M]&lang=en"
op_depar = "https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00017A_000009/~latest.csv?granularity=TIME_PERIOD[M]&lang=en"

calls = [pass_t, gm_t, op_t, pass_arr, gm_arr, op_arr, pass_depar, gm_depar, op_depar]

In [4]:

df_pass_t = pd.read_csv(u.get_data_from_API_call(pass_t))
df_gm_t = pd.read_csv(u.get_data_from_API_call(gm_t))
df_op_t = pd.read_csv(u.get_data_from_API_call(op_t))

df_pass_arr = pd.read_csv(u.get_data_from_API_call(pass_arr))
df_gm_arr = pd.read_csv(u.get_data_from_API_call(gm_arr))
df_op_arr = pd.read_csv(u.get_data_from_API_call(op_arr))

df_pass_depar = pd.read_csv(u.get_data_from_API_call(pass_depar))
df_gm_depar = pd.read_csv(u.get_data_from_API_call(gm_depar))
df_op_depar = pd.read_csv(u.get_data_from_API_call(op_depar))

/tmp/ipykernel_68720/4020862585.py:2: DtypeWarning: Columns (19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_gm_t = pd.read_csv(u.get_data_from_API_call(gm_t))
/tmp/ipykernel_68720/4020862585.py:5: DtypeWarning: Columns (19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pass_arr = pd.read_csv(u.get_data_from_API_call(pass_arr))
/tmp/ipykernel_68720/4020862585.py:6: DtypeWarning: Columns (19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_gm_arr = pd.read_csv(u.get_data_from_API_call(gm_arr))
/tmp/ipykernel_68720/4020862585.py:9: DtypeWarning: Columns (19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pass_depar = pd.read_csv(u.get_data_from_API_call(pass_depar))
/tmp/ipykernel_68720/4020862585.py:10: DtypeWarning: Columns (19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_gm_depar = pd.read_csv(u.get_data_from_API_call(gm_depar))

In [ ]:
"""
# Load DataFrames from saved CSV files
df_pass_t = pd.read_csv('./save/df_pass_t.csv')
df_gm_t = pd.read_csv('./save/df_gm_t.csv')
df_op_t = pd.read_csv('./save/df_op_t.csv')

df_pass_arr = pd.read_csv('./save/df_pass_arr.csv')
df_gm_arr = pd.read_csv('./save/df_gm_arr.csv')
df_op_arr = pd.read_csv('./save/df_op_arr.csv')

df_pass_depar = pd.read_csv('./save/df_pass_depar.csv')
df_gm_depar = pd.read_csv('./save/df_gm_depar.csv')
df_op_depar = pd.read_csv('./save/df_op_depar.csv')
"""

/tmp/ipykernel_72715/845782304.py:3: DtypeWarning: Columns (19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_gm_t = pd.read_csv('./save/df_gm_t.csv')
/tmp/ipykernel_72715/845782304.py:7: DtypeWarning: Columns (19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_gm_arr = pd.read_csv('./save/df_gm_arr.csv')
/tmp/ipykernel_72715/845782304.py:11: DtypeWarning: Columns (19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_gm_depar = pd.read_csv('./save/df_gm_depar.csv')

In [5]:
dfs = [
    df_pass_t,
    df_gm_t, 
    df_op_t,
    df_pass_arr,
    df_gm_arr,
    df_op_arr,
    df_pass_depar,
    df_gm_depar,
    df_op_depar
]

In [6]:
for df in dfs:
    df.drop(columns=df.columns[df.columns.str.endswith("#es") | df.columns.str.endswith("#en")], inplace=True)
    df.drop(columns=['ESTADO_OBSERVACION_CODE'], inplace=True)

In [7]:
pass_t = pd.concat([df_pass_t, df_pass_arr, df_pass_depar])
op_t = pd.concat([df_op_t, df_op_arr, df_op_depar])
gm_t = pd.concat([df_gm_t, df_gm_arr, df_gm_depar])

g_t = gm_t.loc[gm_t['MEDIDAS_CODE'] == 'MERCANCIA'].copy(deep=True)

m_t = gm_t.loc[gm_t['MEDIDAS_CODE'] == 'CORREO'].copy(deep=True)

g_t.drop('MEDIDAS_CODE', axis=1, inplace=True)
m_t.drop('MEDIDAS_CODE', axis=1, inplace=True)

In [8]:
df_pass_t

,SERVICIO_AEREO_CODE,MEDIDAS_CODE,MOVIMIENTO_AERONAVE_CODE,TIME_PERIOD_CODE,AEROPUERTO_BASE_CODE,AEROPUERTO_ESCALA_CODE,OBS_VALUE
0,COMMERCIAL,PASAJEROS,_T,2012-M09,ES_GCTS,FOREIGN,540689.0
1,COMMERCIAL,PASAJEROS,_T,2012-M10,ES_GCTS,FOREIGN,677292.0
2,COMMERCIAL,PASAJEROS,_T,2012-M11,ES_GCTS,FOREIGN,701275.0
3,COMMERCIAL,PASAJEROS,_T,2012-M12,ES_GCTS,FOREIGN,679868.0
4,COMMERCIAL,PASAJEROS,_T,2013-M01,ES_GCTS,FOREIGN,684043.0
...,...,...,...,...,...,...,...
2762419,SCHEDULED,PASAJEROS,_T,2012-M04,ES_GCGM,RU,NaN
2762420,SCHEDULED,PASAJEROS,_T,2012-M05,ES_GCGM,RU,NaN
2762421,SCHEDULED,PASAJEROS,_T,2012-M06,ES_GCGM,RU,NaN
2762422,SCHEDULED,PASAJEROS,_T,2012-M07,ES_GCGM,RU,NaN
2762423,SCHEDULED,PASAJEROS,_T,2012-M08,ES_GCGM,RU,NaN

In [9]:
# For some reason the operations table changes the name of the column of the stopover airport
op_t.rename({'AEROPUERTO_ORIGEN_DESTINO_CODE': 'AEROPUERTO_ESCALA_CODE'}, axis=1, inplace=True)

Unlike with TrafficPerTerritory, the datasets for each observed value do not have the same destination airports, so we will have to do a full outer join

In [10]:
print(op_t.shape[0] == pass_t.shape[0])
print(op_t.shape[0])
print(pass_t.shape[0])

False
4284576
8268480

In [11]:
set_pass = set(pass_t['AEROPUERTO_ESCALA_CODE'].unique())
set_op = set(op_t['AEROPUERTO_ESCALA_CODE'].unique())

only_in_A = set_pass - set_op
only_in_B = set_op - set_pass
in_both = set_pass & set_op

In [12]:
print("Only in passenger:", only_in_A)
print("Only in operations:", only_in_B)
print("In both:", in_both)

Only in passenger: {'NO_ENBO', 'GB_EGLL', 'FI_EFKU', 'FR_LFRG', 'UA_O', 'NO_ENBR', 'LV_EVRA', 'GM_GBYD', 'ES_LEPA', 'RO_LROP', 'NO_ENCN', 'DE_ETNL', 'NO_ENTC', 'SE_ESSD', 'ES_LESA', 'RU_UUDD', 'IT_LIPH', 'EE_EETN', 'EE', 'NO_ENHD', 'SE_ESMS', 'GB_EGTE', 'VE', 'SE_ESMT', 'FR_LFBD', 'PL_EPPO', 'ES_LEJR', 'GB_EGCN', 'PL_EPKK', 'CH_LSGG', 'AT_LOWG', 'IS', 'RU_UUWW', 'UA_UKBB', 'LT', 'DE_EDDC', 'PT_LPPD', 'UA', 'AT_LOWS', 'DE_EDLW', 'ES41', 'IE_EIKN', 'VE_O', 'CV', 'SN_O', 'LT_EYVI', 'HU_LHBP', 'IS_O', 'NO_ENVA', 'PT_LPFR', 'DE_EDRZ', 'IT_LIRN', 'FI_EFTU', 'ES_LELN', 'IE_EINN', 'NO_ENAL', 'ES_LEXJ', 'IT_LIRP', 'SE_ESSP', 'FR_LFBO', 'FI_EFOU', 'HU', 'SK_O', 'SE_ESKN', 'ES_LEVX', 'GB_EGPD', 'ES_LEVT', 'DK_EKAH', 'FI_EFVA', 'LT_O', 'ES_LECO', 'NO_ENZV', 'FR_LFOB', 'MA_GMMX', 'ES_LEVD', 'PT_LPPR', 'PL_EPGD', 'ES_LEGR', 'ES_LEPP', 'RU', 'SE_ESNN', 'SE_ESOE', 'GB_EGNV', 'PT_LPMA', 'CV_GVNP', 'SE_ESOK', 'ES53', 'FR_LFJL', 'DE_EDVK', 'PL_EPWR', 'NO_ENML', 'CV_O', 'RO', 'VE_SVMI', 'BE_EBOS', 'CV_GVAC', 'FR_LFRB', 'FI_EFTP', 'SK_LZIB', 'SE_ESMX', 'ES22', 'CV_GVBA', 'NO_ENEV', 'IT_LIPX', 'GB_EGSH', 'SE_ESPA', 'DE_EDSB', 'RU_ULLI', 'HU_O', 'ES_LEGE', 'RU_UUEE', 'MA_GMAD', 'DK_EKYT', 'NO_ENRY', 'DE_EDDR', 'ES53_O', 'GB_EGNH', 'RU_O', 'DE_EDJA', 'MA_GMMH', 'GB_EGMC', 'LV', 'GM', 'BE_EBLG', 'FR_LFQQ', 'FR_LFML', 'DE_EDDE', 'PL_EPMO', 'RO_O', 'SK', 'SE_ESMQ', 'NL_EHBK', 'IS_BIKF', 'FR_LFLL', 'SE_ESGJ', 'ES41_O', 'SE_ESNU', 'DE_EDNY', 'SN', 'GB_EGNJ', 'NO_ENTO', 'NL_EHGG', 'SN_GOOY', 'ES13', 'AT_LOWL'}
Only in operations: {'ES704_O', 'ES_GCLB', 'ES11_O'}
In both: {'DE_EDDV', 'MR', 'PT_O', 'IE_EICK', 'GB_EGAA', 'IT_O', 'ES_GCFV', 'CH_LSZH', 'DE_EDDM', 'ES_LEST', 'ES_LEBB', 'DK_EKBI', 'GB_EGHH', 'IT_LIRF', 'ES61', 'ES_XES70_O', 'ES_GCGM', 'NL_EHAM', 'ES709_O', 'FR_LFRS', 'GB_EGKK', 'ES_XES70', 'SE_ESGG', 'FOREIGN', 'GB_EGNT', 'FI_EFHK', 'PL_O', 'CZ_LKPR', 'DE_EDDF', 'ES30', 'ES24_O', 'DE_EDDT', 'ES21', 'LU_ELLX', 'MR_O', 'GB', 'ES704', 'FI', 'AT', 'ES', 'DE_EDDS', 'MA_GMMN', 'IT_LIMC', 'BE_EBCI', 'NL', 'PT', 'GB_EGGD', 'NO_ENGM', 'ES_LEAS', 'IT', 'ES30_O', 'DK_EKCH', 'NL_EHRD', 'PL_EPKT', 'CH', 'SE_ESSA', 'ES12', 'DE_EDDH', 'ES24', 'ES52_O', 'MA_GMML', 'FR', 'ES21_O', 'DE_EDDL', 'NO', 'ES705', 'AT_O', 'PT_LPPT', 'IE', 'ES51', 'PL_EPWA', 'GB_O', 'DE_EDDP', 'DE_O', 'ES_LEBL', 'ES51_O', 'IE_O', 'ES_GCLA', 'ES70', 'ES11', 'ES_LEZG', 'DE_EDDW', '_O', 'GB_EGNM', 'SE', 'NO_O', 'GB_EGCC', 'FR_O', 'DE_EDDN', 'GB_EGPH', 'GB_EGPF', 'GB_EGNX', 'FR_LFPG', 'GB_EGFF', 'BE', 'MR_GQPP', 'ES52', 'PL', 'IT_LIPE', 'ES708', 'ES_GCTS', 'ES706', 'ES703', 'AT_LOWW', 'CH_O', 'DE_EDDK', 'ES_LEAL', 'MR_GQNO', 'MA', 'GB_EGSS', 'SE_O', 'ES_LEMG', 'BE_EBBR', 'ES61_O', 'MA_O', 'ES_GCLP', 'CZ', 'IT_LIME', 'ES_LEZL', 'NL_EHEH', 'DE_EDLV', 'ES_GCXO', 'ES709', 'BE_O', 'ES706_O', 'DE', 'DE_EDFH', 'ES_GCHI', 'ES705_O', 'ES_GCRR', 'GB_EGBB', 'FR_LFPO', 'LU', 'ES_LEMD', 'FR_LFSB', 'DK', 'GB_EGGW', 'IE_EIDW', 'GB_EGGP', 'FI_O', 'GB_EGPK', 'ES_LEVC', 'NL_O', 'DE_EDLP', 'DE_EDDB', 'ES707', 'CZ_O', 'DK_O', 'DE_EDDG'}

First fill na with 0 in the dataframes we are going to merge, since we are doing an outer join and the result will contain nan values, we dont want to confuse nan because is 0 and nan because the observed value doesnt belong to the destination airport. In theory it doesnt matter because in the end we will fill all with 0 anyways, but we do it at first to check if the union is correct

In [13]:
pass_t['OBS_VALUE'] = pass_t['OBS_VALUE'].fillna(0)
op_t['OBS_VALUE'] = op_t['OBS_VALUE'].fillna(0)

In [14]:
pass_t

,SERVICIO_AEREO_CODE,MEDIDAS_CODE,MOVIMIENTO_AERONAVE_CODE,TIME_PERIOD_CODE,AEROPUERTO_BASE_CODE,AEROPUERTO_ESCALA_CODE,OBS_VALUE
0,COMMERCIAL,PASAJEROS,_T,2012-M09,ES_GCTS,FOREIGN,540689.0
1,COMMERCIAL,PASAJEROS,_T,2012-M10,ES_GCTS,FOREIGN,677292.0
2,COMMERCIAL,PASAJEROS,_T,2012-M11,ES_GCTS,FOREIGN,701275.0
3,COMMERCIAL,PASAJEROS,_T,2012-M12,ES_GCTS,FOREIGN,679868.0
4,COMMERCIAL,PASAJEROS,_T,2013-M01,ES_GCTS,FOREIGN,684043.0
...,...,...,...,...,...,...,...
2753023,SCHEDULED,PASAJEROS,DEPARTURE,2025-M05,ES_GCGM,ES709,2827.0
2753024,SCHEDULED,PASAJEROS,DEPARTURE,2025-M06,ES_GCGM,ES709,2854.0
2753025,SCHEDULED,PASAJEROS,DEPARTURE,2025-M07,ES_GCGM,ES709,3004.0
2753026,SCHEDULED,PASAJEROS,DEPARTURE,2025-M08,ES_GCGM,ES709,3672.0
2753027,SCHEDULED,PASAJEROS,DEPARTURE,2025-M09,ES_GCGM,ES709,2956.0

In [15]:
df_f = pass_t.merge(op_t, 
                    on=['AEROPUERTO_BASE_CODE', 'AEROPUERTO_ESCALA_CODE', 'MOVIMIENTO_AERONAVE_CODE', 'SERVICIO_AEREO_CODE', 'TIME_PERIOD_CODE'], 
                    suffixes=("", "_op"),
                    how="outer")
df_f.drop(columns=[col for col in df_f.columns if col.endswith('op') and not col in ['OBS_VALUE_op']], inplace=True)

Because we filled nan with 0 previous to the join, there shouldnt be any rows where both observed values are null

In [16]:

df_f.loc[pd.isna(df_f['OBS_VALUE_op']) & pd.isna(df_f['OBS_VALUE'])]

Empty DataFrame
Columns: [SERVICIO_AEREO_CODE, MEDIDAS_CODE, MOVIMIENTO_AERONAVE_CODE, TIME_PERIOD_CODE, AEROPUERTO_BASE_CODE, AEROPUERTO_ESCALA_CODE, OBS_VALUE, OBS_VALUE_op]
Index: []

In [17]:
# We dont need this
df_f.drop('MEDIDAS_CODE', axis=1, inplace=True)

The null values in operations should be way higher than in passengers, because passengers has that much more airports

In [18]:
print(f"Number of null observed values in operation after join: {len(df_f.loc[pd.isna(df_f['OBS_VALUE_op'])])}")
print(f"Number of null observed values in passengers after join: {len(df_f.loc[pd.isna(df_f['OBS_VALUE'])])}")

Number of null observed values in operation after join: 4077864
Number of null observed values in passengers after join: 93960

In fact, to check if everything is correct, the number of null in OBS_VALUE in the join should be:

In passengers: (number of airports that passenger doesnt have compared to operations) * (len unique rest of columns used in month)\
In operations: (number of airports that operations doesnt have compared to passengers) * (len unique rest of columns used in month)

And the total number of rows in the join dataset should be:
(number of rows of the dataset with more airports: passenger) + (number of null OBS_VALUE in passenger)

In [19]:
pass_t.shape[0] + len(df_f.loc[pd.isna(df_f['OBS_VALUE'])]) == df_f.shape[0]

True

In [20]:
df_f.shape[0]

8362440

In [21]:
df_f.isna().sum()

SERVICIO_AEREO_CODE               0
MOVIMIENTO_AERONAVE_CODE          0
TIME_PERIOD_CODE                  0
AEROPUERTO_BASE_CODE              0
AEROPUERTO_ESCALA_CODE            0
OBS_VALUE                     93960
OBS_VALUE_op                4077864
dtype: int64

With this we can safely conclude that the datasets are correctly joined, now we do the same for goods and mail, change names for Id, rename columns and we should have TrafficPerAirport

Again we found out that the goods and mail dataset doesnt have the same number of rows as passengers or operations, so again we must do an outer join

In [22]:
print(g_t.shape[0] == m_t.shape[0])
print(pass_t.shape[0] == g_t.shape[0])
print(op_t.shape[0] == g_t.shape[0])

print(g_t.shape[0])
print(pass_t.shape[0])
print(op_t.shape[0])

True
False
False
5102028
8268480
4284576

In [23]:
g_t['OBS_VALUE'] = g_t['OBS_VALUE'].fillna(0)

m_t['OBS_VALUE'] = m_t['OBS_VALUE'].fillna(0)

In [24]:
df_f = df_f.merge(g_t, 
                    on=['AEROPUERTO_BASE_CODE', 'AEROPUERTO_ESCALA_CODE', 'MOVIMIENTO_AERONAVE_CODE', 'SERVICIO_AEREO_CODE', 'TIME_PERIOD_CODE'], 
                    suffixes=("", "_g"),
                    how='outer')
df_f.drop(columns=[col for col in df_f.columns if col.endswith('g') and not col in ['OBS_VALUE_g']], inplace=True)

In [25]:
df_f.shape[0]

9114120

In [26]:
df_f.isna().sum()

SERVICIO_AEREO_CODE               0
MOVIMIENTO_AERONAVE_CODE          0
TIME_PERIOD_CODE                  0
AEROPUERTO_BASE_CODE              0
AEROPUERTO_ESCALA_CODE            0
OBS_VALUE                    845640
OBS_VALUE_op                4829544
OBS_VALUE_g                 4012092
dtype: int64

In [27]:
df_f = df_f.merge(m_t, 
                    on=['AEROPUERTO_BASE_CODE', 'AEROPUERTO_ESCALA_CODE', 'MOVIMIENTO_AERONAVE_CODE', 'SERVICIO_AEREO_CODE', 'TIME_PERIOD_CODE'], 
                    suffixes=("", "_m"),
                    how='outer')
df_f.drop(columns=[col for col in df_f.columns if col.endswith('m') and not col in ['OBS_VALUE_m']], inplace=True)

In [28]:
df_f.isna().sum()

SERVICIO_AEREO_CODE               0
MOVIMIENTO_AERONAVE_CODE          0
TIME_PERIOD_CODE                  0
AEROPUERTO_BASE_CODE              0
AEROPUERTO_ESCALA_CODE            0
OBS_VALUE                    845640
OBS_VALUE_op                4829544
OBS_VALUE_g                 4012092
OBS_VALUE_m                 4012092
dtype: int64

Since the number of rows aumented after the outer join, it must mean that goods and mail have some airports that passengers and operations dont, so lets check

In [29]:
df_f.loc[((pd.isna(df_f['OBS_VALUE'])) & (pd.isna(df_f['OBS_VALUE_op']))) & (~pd.isna(df_f['OBS_VALUE_m'])), 'AEROPUERTO_ESCALA_CODE'].unique()

array(['BR', 'BR_O', 'BR_SBKP', 'CL', 'CL_SCEL', 'CU', 'CU_MUHA', 'CU_O',
       'ES42', 'ES_LERL', 'LR', 'LR_GLRB', 'NG', 'NG_DNAA', 'NG_O',
       'SE_ESNZ', 'SE_ESOW', 'SG', 'SG_WSSS', 'SL', 'SL_GFLL', 'SN_GOBD',
       'US', 'US_KBDL', 'US_KBGR', 'US_KIAH', 'US_KMCO', 'US_KMIA',
       'US_KMSY', 'US_O'], dtype=object)

In [30]:
df_f.loc[((pd.isna(df_f['OBS_VALUE'])) & (pd.isna(df_f['OBS_VALUE_op']))) & (~pd.isna(df_f['OBS_VALUE_m']))]

,SERVICIO_AEREO_CODE,MOVIMIENTO_AERONAVE_CODE,TIME_PERIOD_CODE,AEROPUERTO_BASE_CODE,AEROPUERTO_ESCALA_CODE,OBS_VALUE,OBS_VALUE_op,OBS_VALUE_g,OBS_VALUE_m
37584,COMMERCIAL,ARRIVAL,2004-M01,ES70,BR,NaN,NaN,0.0,0.0
37585,COMMERCIAL,ARRIVAL,2004-M02,ES70,BR,NaN,NaN,0.0,0.0
37586,COMMERCIAL,ARRIVAL,2004-M03,ES70,BR,NaN,NaN,0.0,0.0
37587,COMMERCIAL,ARRIVAL,2004-M04,ES70,BR,NaN,NaN,0.0,0.0
37588,COMMERCIAL,ARRIVAL,2004-M05,ES70,BR,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...
9101587,SCHEDULED,_T,2025-M05,ES_GCXO,US_O,NaN,NaN,0.0,0.0
9101588,SCHEDULED,_T,2025-M06,ES_GCXO,US_O,NaN,NaN,0.0,0.0
9101589,SCHEDULED,_T,2025-M07,ES_GCXO,US_O,NaN,NaN,0.0,0.0
9101590,SCHEDULED,_T,2025-M08,ES_GCXO,US_O,NaN,NaN,0.0,0.0
9101591,SCHEDULED,_T,2025-M09,ES_GCXO,US_O,NaN,NaN,0.0,0.0

In [31]:
set_g = set(g_t['AEROPUERTO_ESCALA_CODE'].unique())

g_op = set_g - set_op
op_g = set_op - set_g
op_a_g = set_g & set_op

g_pass = set_g - set_pass
pass_g = set_pass - set_g
g_a_pass = set_g & set_pass

In [32]:
print(f"Only in passenger between pass and goods: {pass_g}")
print(f"Only in goods between pass and goods: {g_pass}")
print(f"Both pass and goods: {g_a_pass}")

Only in passenger between pass and goods: {'NO_ENBO', 'IE_EICK', 'FI_EFKU', 'FR_LFRG', 'UA_O', 'LV_EVRA', 'GB_EGHH', 'RO_LROP', 'NO_ENCN', 'IT_LIRF', 'DE_ETNL', 'NO_ENTC', 'SE_ESSD', 'ES_LESA', 'IT_LIPH', 'EE_EETN', 'EE', 'NO_ENHD', 'GB_EGTE', 'SE_ESMT', 'FR_LFBD', 'ES709_O', 'FR_LFRS', 'PL_EPPO', 'ES_LEJR', 'PL_EPKK', 'CH_LSGG', 'AT_LOWG', 'PL_O', 'ES24_O', 'IS', 'RU_UUWW', 'UA_UKBB', 'LT', 'DE_EDDC', 'PT_LPPD', 'UA', 'AT_LOWS', 'DE_EDLW', 'MA_GMMN', 'ES41', 'IE_EIKN', 'VE_O', 'BE_EBCI', 'LT_EYVI', 'GB_EGGD', 'NL_EHRD', 'HU_LHBP', 'PL_EPKT', 'IS_O', 'NO_ENVA', 'PT_LPFR', 'DE_EDRZ', 'ES52_O', 'IT_LIRN', 'FI_EFTU', 'ES_LELN', 'IE_EINN', 'NO_ENAL', 'ES_LEXJ', 'IT_LIRP', 'SE_ESSP', 'FR_LFBO', 'HU', 'PL_EPWA', 'SK_O', 'SE_ESKN', 'GB_EGPD', 'ES_LEVT', 'DK_EKAH', 'FI_EFVA', 'LT_O', 'FR_LFOB', 'MA_GMMX', 'ES_LEVD', 'PT_LPPR', 'PL_EPGD', 'ES_LEGR', 'ES_LEPP', 'SE_ESNN', 'SE_ESOE', 'GB_EGNV', 'PT_LPMA', 'FR_LFPG', 'IT_LIPE', 'PL', 'FR_LFJL', 'DE_EDVK', 'PL_EPWR', 'NO_ENML', 'CV_O', 'RO', 'BE_EBOS', 'FR_LFRB', 'FI_EFTP', 'SK_LZIB', 'SE_ESMX', 'IT_LIME', 'ES22', 'DE_EDLV', 'NL_EHEH', 'NO_ENEV', 'IT_LIPX', 'GB_EGSH', 'DE_EDSB', 'RU_ULLI', 'ES706_O', 'DE_EDFH', 'HU_O', 'ES_LEGE', 'DK_EKYT', 'NO_ENRY', 'DE_EDDR', 'GB_EGNH', 'DE_EDJA', 'ES705_O', 'FR_LFPO', 'GB_EGMC', 'LV', 'FR_LFML', 'DE_EDDE', 'FR_LFQQ', 'PL_EPMO', 'RO_O', 'SK', 'GB_EGGP', 'SE_ESMQ', 'NL_EHBK', 'IS_BIKF', 'FR_LFLL', 'SE_ESGJ', 'DE_EDLP', 'ES41_O', 'DE_EDDG', 'DE_EDNY', 'GB_EGNJ', 'NL_EHGG', 'ES13', 'AT_LOWL'}
Only in goods between pass and goods: {'SE_ESNZ', 'ES42', 'US_KIAH', 'CL', 'US_KBDL', 'CU', 'NG_DNAA', 'NG_O', 'US_KMCO', 'SG', 'SG_WSSS', 'LR', 'CU_MUHA', 'US_O', 'SL', 'SL_GFLL', 'LR_GLRB', 'US', 'SE_ESOW', 'NG', 'BR_O', 'CL_SCEL', 'US_KMIA', 'ES_LERL', 'BR_SBKP', 'BR', 'CU_O', 'SN_GOBD', 'US_KMSY', 'US_KBGR'}
Both pass and goods: {'DE_EDDV', 'MR', 'PT_O', 'GB_EGLL', 'GB_EGAA', 'IT_O', 'ES_GCFV', 'CH_LSZH', 'DE_EDDM', 'NO_ENBR', 'ES_LEBB', 'ES_LEST', 'GM_GBYD', 'ES_LEPA', 'DK_EKBI', 'ES61', 'ES_XES70_O', 'RU_UUDD', 'ES_GCGM', 'SE_ESMS', 'NL_EHAM', 'VE', 'GB_EGKK', 'GB_EGCN', 'ES_XES70', 'SE_ESGG', 'FOREIGN', 'GB_EGNT', 'FI_EFHK', 'CZ_LKPR', 'DE_EDDF', 'ES30', 'DE_EDDT', 'ES21', 'LU_ELLX', 'MR_O', 'GB', 'ES704', 'FI', 'AT', 'ES', 'DE_EDDS', 'IT_LIMC', 'CV', 'NL', 'SN_O', 'PT', 'NO_ENGM', 'ES_LEAS', 'IT', 'ES30_O', 'DK_EKCH', 'CH', 'SE_ESSA', 'ES12', 'DE_EDDH', 'ES24', 'MA_GMML', 'FR', 'ES21_O', 'DE_EDDL', 'NO', 'ES705', 'AT_O', 'PT_LPPT', 'IE', 'ES51', 'FI_EFOU', 'GB_O', 'DE_EDDP', 'ES_LEVX', 'DE_O', 'ES_LEBL', 'ES51_O', 'IE_O', 'ES_GCLA', 'ES70', 'ES_LECO', 'ES11', 'ES_LEZG', 'DE_EDDW', 'NO_ENZV', '_O', 'GB_EGNM', 'SE', 'NO_O', 'GB_EGCC', 'FR_O', 'RU', 'DE_EDDN', 'GB_EGPH', 'GB_EGPF', 'GB_EGNX', 'GB_EGFF', 'BE', 'CV_GVNP', 'MR_GQPP', 'ES52', 'SE_ESOK', 'ES53', 'ES708', 'ES_GCTS', 'ES706', 'ES703', 'AT_LOWW', 'CH_O', 'DE_EDDK', 'VE_SVMI', 'MR_GQNO', 'MA', 'ES_LEAL', 'GB_EGSS', 'SE_O', 'ES_LEMG', 'BE_EBBR', 'ES61_O', 'CV_GVAC', 'MA_O', 'ES_GCLP', 'CZ', 'CV_GVBA', 'ES_LEZL', 'ES_GCXO', 'ES709', 'BE_O', 'SE_ESPA', 'DE', 'RU_UUEE', 'MA_GMAD', 'ES_GCHI', 'ES53_O', 'RU_O', 'ES_GCRR', 'MA_GMMH', 'GB_EGBB', 'LU', 'GM', 'ES_LEMD', 'FR_LFSB', 'BE_EBLG', 'DK', 'GB_EGGW', 'IE_EIDW', 'FI_O', 'GB_EGPK', 'ES_LEVC', 'NL_O', 'DE_EDDB', 'ES707', 'CZ_O', 'SE_ESNU', 'DK_O', 'SN', 'NO_ENTO', 'SN_GOOY'}

In [33]:
set(df_f.loc[((pd.isna(df_f['OBS_VALUE'])) & (pd.isna(df_f['OBS_VALUE_op']))) & (~pd.isna(df_f['OBS_VALUE_m'])), 'AEROPUERTO_ESCALA_CODE'].unique()) - g_pass

set()

Finally since we already checked everything is alright we can fill al nan values with 0

In [34]:
df_f.fillna(0, inplace=True)

In [37]:
territory = pd.read_csv('../../data/Final_Territory.csv')
airservice = pd.read_csv('../../data/AirService.csv')
aircraftmovement = pd.read_csv('../../data/Final_AircraftMovement.csv')
airport = pd.read_csv('../../data/Airport.csv')

In [38]:
# Replace values in df_f["TERRITORIO_CODE"] with corresponding TerritoryId
df_f["AEROPUERTO_BASE_CODE"] = df_f["AEROPUERTO_BASE_CODE"].map(dict(zip(airport["AirportCode"], airport["AirportId"])))

# Replace values in df_f["AEROPUERTO_ESCALA_CODE"] with corresponding TerritoryId
df_f["AEROPUERTO_ESCALA_CODE"] = df_f["AEROPUERTO_ESCALA_CODE"].map(dict(zip(airport["AirportCode"], airport["AirportId"])))
# Delete rows where AEROPUERTO_ESCALA_CODE hasnt matched (deleted territories like Total)
df_f.dropna(inplace=True)

df_f["AEROPUERTO_ESCALA_CODE"] = df_f["AEROPUERTO_ESCALA_CODE"].astype(int)

df_f["SERVICIO_AEREO_CODE"] = df_f["SERVICIO_AEREO_CODE"].map(dict(zip(airservice['AirServiceCode'], airservice['AirServiceId'])))

df_f["MOVIMIENTO_AERONAVE_CODE"] = df_f["MOVIMIENTO_AERONAVE_CODE"].map(dict(zip(aircraftmovement['AircraftMovementCode'], aircraftmovement['AircraftMovementId'])))

In [39]:
df_f['TIME_PERIOD_CODE'] = pd.to_datetime(df_f['TIME_PERIOD_CODE'].str.replace('M', ''), format='%Y-%m')

In [40]:
df_f

,SERVICIO_AEREO_CODE,MOVIMIENTO_AERONAVE_CODE,TIME_PERIOD_CODE,AEROPUERTO_BASE_CODE,AEROPUERTO_ESCALA_CODE,OBS_VALUE,OBS_VALUE_op,OBS_VALUE_g,OBS_VALUE_m
1015812,0,0,2004-01-01,143.0,21,0.0,0.0,0.0,0.0
1015813,0,0,2004-02-01,143.0,21,0.0,0.0,0.0,0.0
1015814,0,0,2004-03-01,143.0,21,0.0,0.0,0.0,0.0
1015815,0,0,2004-04-01,143.0,21,0.0,0.0,0.0,0.0
1015816,0,0,2004-05-01,143.0,21,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
9110983,3,2,2025-05-01,183.0,187,1854.0,0.0,0.0,0.0
9110984,3,2,2025-06-01,183.0,187,2458.0,0.0,0.0,0.0
9110985,3,2,2025-07-01,183.0,187,1328.0,0.0,1430.0,0.0
9110986,3,2,2025-08-01,183.0,187,2667.0,0.0,7599.0,0.0
9110987,3,2,2025-09-01,183.0,187,2184.0,0.0,7250.0,0.0

In [41]:
df_f.rename({
    'AEROPUERTO_BASE_CODE': 'BaseAirportId',
    'AEROPUERTO_ESCALA_CODE': 'StopoverAirportId',
    'MOVIMIENTO_AERONAVE_CODE': 'AircraftMovementId',
    'SERVICIO_AEREO_CODE': 'AirServiceId',
    'TIME_PERIOD_CODE': 'Month',
    'OBS_VALUE': 'Passengers',
    'OBS_VALUE_g': 'Goods',
    'OBS_VALUE_m': 'Mail',
    'OBS_VALUE_op': 'Operations'
}, axis=1, inplace=True)

In [42]:

for col in ['BaseAirportId', 'Passengers', 'Goods', 'Mail', 'Operations']:
    df_f[col] = df_f[col].astype(int)

In [43]:
df_f.to_csv('../../data/Final_TrafficPerAirport.csv', index=False)